version: '3'
services:

  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: nemosanima/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: nemosanima/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx_local.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend


volumes:
  static_value:
  media_value:
  data_value:
  postgres_data:
  redoc:
