version: '3'
services:

  db:
    image: postgres
    restart: always
    volumes:
      # создаем volume postgres_data внутри контейнера db, который будет содержать данные базы данных.
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: nemosanima/footgram_backend_local
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: nemosanima/footgram_frontend_local
    volumes:
      # локальная директория "../frontend/" будет монтироваться в путь
      # "/app/result_build/" внутри контейнера.
      # Слева от символа ":" указывается путь на моей машине, а справа - путь внутри контейнера.
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      # nginx_local.conf вмонтирую в /etc/nginx/conf.d/default.conf
      # чтобы позволить контейнеру использовать этот файл для настройки Nginx.
      - ./nginx_local.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      # Volumes для media и static
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      # Для документации по api
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend


volumes:
  static_value:
  media_value:
  postgres_data: