# Generated by Django 4.2.1 on 2023-05-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_shoppingcart_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientRecipe',
            new_name='RecipeIngredient',
        ),
    ]
