name: Foodgram workflow

on: [push]

jobs:
  test_flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        users: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return flake8
          pip install -r requirements.txt
      - name: Test flake8
        run: |
          cd backend
          flake8 .
          

